import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Helmet } from "react-helmet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KW Landing page Figma NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
